### PR TITLE
fix: ACNA-894 - Action running in local cannot be debugged

### LINKED ISSUE #128: ACNA-894 - Action running in local cannot be debugged
### Expected Behaviour
Create an app, run the app with "--local", add a breakpoint in run the action and run the debugger. When action is executed, the debugger pause the execution.

### Actual Behaviour
The debugger does not start.

#### Steps to Reproduce
On a fresh new app, run `aio app run --local`.
Open VC Code and hit the `Run Action:<app>-0.0.1/<action>` button from the debugger.

The debugger starts but crashes immediately: 

```
Error: Action not found: <app>-0.0.1/<action>
    at AgentMgr.peekAction (/Users/acapt/work/dev/helix/playground/test/node_modules/@openwhisk/wskdebug/src/agentmgr.js:104:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### Environment Info
```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.60 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Virtualization:
    Docker: 19.03.12 - /usr/local/bin/docker
  npmGlobalPackages:
    @adobe/aio-cli: 3.7.0
```

#### Workaround

I found the issue: the .env file contains the `runtime_auth` and `runtime_namespace` twice (almost lower case and uppercase) and the debugger use the lowercase one while it should use the uppercase one.
In fact, the "local override" does not work anymore because of the letters case.

```
AIO_runtime_auth=abc
AIO_runtime_namespace=def
SERVICE_API_KEY=
AIO_LAUNCH_URL_PREFIX=https://experience.adobe.com/?devMode=true#/custom-apps/?localDevUrl=
AIO_RUNTIME_APIHOST=http://localhost:3233
AIO_RUNTIME_AUTH=xyz
AIO_RUNTIME_NAMESPACE=guest
```

Workaround is to stop the server, edit the `.env` and uppercase the 2 variables: `AIO_RUNTIME_AUTH` and `AIO_RUNTIME_NAMESPACE`.

cc @meryllblanchet

### PR DESCRIPTION
**Pull request by shazron**
Fixes #128

## How Has This Been Tested?

```
npm test
```
and
```
aio app init
aio app run --local
```
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -371,13 +371,29 @@ function saveAndReplaceDotEnvCredentials (dotenvFile, saveFile, apihost, namespa
   fs.moveSync(dotenvFile, saveFile)
   // Only override needed env vars and preserve other vars in .env
   const env = dotenv.parse(fs.readFileSync(saveFile))
-  env.AIO_RUNTIME_APIHOST = apihost
-  env.AIO_RUNTIME_AUTH = auth
-  env.AIO_RUNTIME_NAMESPACE = namespace
-  // existing AIO__ vars might override above AIO_ vars
-  delete env.AIO__RUNTIME_AUTH
```
Comment (moritzraho) [inline lib/utils.js:378]: we should still handle double underscores as config lib treats `AIO_` and `AIO__` in the same way

**Review by moritzraho — COMMENTED** [review]
apart for the `AIO_` vs `AIO__` comment also captured in https://github.com/adobe/aio-lib-core-config/issues/49 , lgtm

File: lib/utils.js (hunk 1 above)
Comment (shazron) [reply lib/utils.js:378]: 👍  because of this quirk: https://github.com/adobe/aio-lib-core-config/issues/49

**Review by moritzraho — APPROVED** [review]
